name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main 

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup OCaml
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: 4.14.x
          opam-depext: true

      - name: Install dependencies
        run: |
          opam install -y js_of_ocaml js_of_ocaml-ppx

      - name: Build project
        run: |
          ./setup.sh
          
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: _build/default/web  # The folder containing our built web files
          branch: gh-pages 
